name: autotools build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-autotools:

    runs-on: ubuntu-latest
    name: Ubuntu

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure CFLAGS=-Werror
    - name: make
      run: make CFLAGS=-Werror
