name: autotools build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-autotools:

    runs-on: ubuntu-latest
    name: Ubuntu
    env:
        CFLAGS: "-Werror"
        CXXFLAGS: "-Werror"

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
