# This Action uses minimal steps to run in ~5 seconds to rapidly:
# look for typos in the codebase using codespell, and
# lint Python code using ruff and provide intuitive GitHub Annotations to contributors.
# https://github.com/codespell-project/codespell#readme
# https://docs.astral.sh/ruff/
name: codespell_and_ruff
on:
  push:
    branches: [master]
  pull_request:
jobs:
  codespell_and_ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install --user codespell[toml] ruff
    - run: codespell **/*.py **/*.txt
    - run: ruff check --output-format=github --target-version=py38 .
